routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Thông báo đơn hàng mới 
// Duyệt đơn hàng
//  

Route::group(['namespace'=>'client'],function(){
	Route::get('/doc-1-thong-bao/{id}','notification_clientController@read_notifi_client')->name('read_notifi_client')->middleware('CheckLogoutUser');
	Route::get('doc-thong-bao',function(){
		\Auth::User()->notifications->markAsRead();
		return redirect()->route('getHome');
	})->name('read_all');
	//Home	
	Route::get('/','HomeController@getHome')->name('getHome')->middleware('CheckLogoutUser');
	Route::get('/test','HomeController@getTest')->name('getTest')->middleware('CheckLogoutUser');
	Route::get('/san-pham-cua-toi','HomeController@mylove')->name('mylove')->middleware('CheckLogoutUser');
	Route::post('/test','HomeController@postTest')->name('postTest')->middleware('CheckLogoutUser');
	Route::get('/san-pham/{id}','DetailproductController@getDetailproduct')->name('getDetailproduct')->middleware('CheckLogoutUser');
	Route::post('/san-pham','DetailproductController@postComment')->name('postComment')->middleware('CheckLogoutUser');
	Route::get('/don-hang-cua-ban','HomeController@myorder')->name('myorder')->middleware('CheckLogoutUser');
	Route::get('/xoa-don-hang-cua-ban','HomeController@xoa_mylove')->name('xoa_mylove')->middleware('CheckLogoutUser');
	Route::get('/cap-nhat-don-hang-cua-ban','HomeController@update_mylove')->name('update_mylove')->middleware('CheckLogoutUser');
	Route::get('/san-pham-ban-yeu-thich','DetailproductController@add_love')->name('add_love')->middleware('CheckLogoutUser');
	// Route::get('/tim-kiem','HomeController@getsearch')->name('getsearch')->middleware('CheckLogoutUser');
	Route::post('/tim-kiem','HomeController@postsearch')->name('postsearch')->middleware('CheckLogoutUser');
	//Cart
	Route::get('/gio-hang','CartController@showCart')->name('showCart')->middleware('CheckLogoutUser');
	Route::post('/gio-hang','CartController@getCart')->name('getCart')->middleware('CheckLogoutUser');
	Route::get('/xoa-gio-hang/{id}','CartController@destroy')->name('deleteCart')->middleware('CheckLogoutUser');
	Route::post('/sua-gio-hang','CartController@update')->name('updateCart')->middleware('CheckLogoutUser');
	Route::get('/don-hang','CartController@index')->name('indexCart')->middleware('CheckLogoutUser');
	Route::get('/cap-nhat-gio-hang','Ajax_edit_cartController@update')->name('editCart')->middleware('CheckLogoutUser');
	Route::get('/xoa-gio-hang','Ajax_edit_cartController@delete')->name('xoaCart')->middleware('CheckLogoutUser');
	Route::get('/them-gio-hang','Ajax_edit_cartController@themCart')->name('themCart')->middleware('CheckLogoutUser');
	// Route::post('/don-hang','CartController@store')->name('insertCart')->middleware('CheckLogoutUser');
	Route::resource('order','CartController')->middleware('CheckLogoutUser');
	//Checkout
	Route::get('/dang-nhap-check','CheckoutController@login_checkout')->name('login_check')->middleware('CheckLogoutUser');
	//Lien He
	Route::post('/post-lien-he','ContactController@lienhe')->name('lienhe');
	Route::get('/lien-he','ContactController@getContact')->name('getContact')->middleware('CheckLogoutUser');
	//Login

	Route::get('/dang-nhap','UserController@getLoginUser')->name('getLoginUser');
	Route::post('/dang-nhap','UserController@postLoginUser')->name('postLoginUser');
	Route::get('/quen-mat-khau','UserController@forget')->name('forget');
	Route::get('/getInfo-facebook/{social}','SocialController@getInfoFacebook')->name('getInfoFacebook');
	Route::get('/check-info-facebook/{social}','SocialController@checkInfoFacebook')->name('checkInfoFacebook');
	Route::get('/login-facebook','UserController@login_facebook');
	Route::get('/dang-nhap/callback','UserController@callback_facebook');	
	Route::post('/dang-nhap/email','UserController@getpassword')->name('getpassword');
	Route::get('/dang-nhap/newpass/','UserController@newpass')->name('newpass');
	Route::post('/dang-nhap/postnewpass/','UserController@postnewpass')->name('postnewpass');


	//Logout
	Route::get('/dang-xuat','UserController@getLogoutUser')->name('getLogoutUser');
	//register
	Route::get('/dang-ky','UserController@create')->name('getAddUser')->middleware('CheckLogoutUser');
	Route::post('/dang-ky','UserController@postcreate')->name('postAddUser')->middleware('CheckLogoutUser');
	Route::get('/kiem-tra','UserController@getcheckout')->name('checkout')->middleware('CheckLogoutUser');
	//category
	Route::group(['namespace'=>'category'],function(){			
		Route::get('/danh-muc/{id}','CategoryController@show')->name('getCate')->middleware('CheckLogoutUser');
		Route::get('/count_prod_by_cate','ajax_count_prod_by_cateController@index')->name('count_prod_by_cate')->middleware('CheckLogoutUser');
	});
	//post quen huyen
	Route::post('/client_post_quan_huyen','Ajax_get_addressController@post_Quan_huyen')->name('post_quan_huyen')->middleware('CheckLogoutUser');
	Route::post('/client_post_phuong_xa','Ajax_get_addressController@post_Phuong_Xa')->name('post_phuong_xa')->middleware('CheckLogoutUser');

	//Blog
	Route::get('/tin-tuc','BlogController@getBlog')->name('getBlog')->middleware('CheckLogoutUser');
	Route::post('/binh-luan','BlogController@postcomment_blog')->name('postcomment_blog')->middleware('CheckLogoutUser');
	Route::get('/xem-chinh-sach','PolicyController@getPolicy')->name('getPolicy')->middleware('CheckLogoutUser');
	Route::get('/xem-bao-hanh','PolicyController@baohanh')->name('baohanh')->middleware('CheckLogoutUser');
	Route::get('/xem-cai-dat','PolicyController@caidat')->name('caidat')->middleware('CheckLogoutUser');
	Route::get('/xem-nang-cap','PolicyController@nangcap')->name('nangcap')->middleware('CheckLogoutUser');
	Route::get('/lien-he','ContactController@getContact')->name('getContact')->middleware('CheckLogoutUser');
	Route::get('/xem-blog/{id}','BlogController@getDetailBlog')->name('getDetailBlog')->middleware('CheckLogoutUser');

	//Payment
	Route::get('/thanh-toan','PaymentControler@getPayment')->name('getPayment')->middleware('CheckLogoutUser');
	Route::group(['middleware' => ['web']], function () {
		Route::post('/thanh-toan','PaymentControler@postPayment')->name('postPayment')->middleware('CheckLogoutUser');	
	});
	
	//Ajax index
	Route::get('/gio-hang-index-sale','HomeController@cart_index_sale')->name('cart_index_sale');
	Route::get('/yeu-thich-index-sale','HomeController@love_index_sale')->name('love_index_sale');
	Route::get('/goi-y-tim-kiem','HomeController@autocomplete')->name('autocomplete');
	//Chinh sach
	
	
});

Route::group(['namespace'=>'admin'],function(){
	Route::group(['prefix'=>'admin'],function(){	
		Route::get('/','AdhomeController@get_list_category')->name('getAdHome')->middleware('CheckLogout');
		Route::post('tim-kiem','AdhomeController@search')->name('search')->middleware('CheckLogout');
		Route::post('tim-kiem-doanh-thu','AdhomeController@searchDoanhThu')->name('searchDoanhThu')->middleware('CheckLogout');
		Route::get('sua-mail','MailController@editMail')->name('editMail')->middleware('CheckLogout');
		Route::get('raw','GraficasController@raw')->name('raw')->middleware('CheckLogout');
		Route::post('ajax-doanh-thu','AdhomeController@AjaxDoanhThu')->name('AjaxdoanhThu')->middleware('CheckLogout');
		Route::post('ajax-doanh-thu-thang','AdhomeController@getDoanhThuThang')->name('getDoanhThuThang')->middleware('CheckLogout');
		//order
		Route::group(['namespace'=>'order'],function(){	
			# Hiển thị danh sách đơn hàng mới admin
			Route::get('/don-hang-moi/{id}','OrderController@show')->name('getListOrder')->middleware('CheckLogout');
			# Hiển thị danh sách sale
			Route::post('/get-list-sale','OrderController@getListSale')->name('getListSale')->middleware('CheckLogout');
			# Chọn sale duyệt
			Route::post('/selectSale','OrderController@selectSale')->name('selectSale')->middleware('CheckLogout');
			# Hiển thị danh sách đơn hàng của sale	
			Route::get('/don-hang-sale/{id}','order_saleController@getListOrderSale')->name('getListOrderSale')->middleware('CheckLogout');
			# Hiển thị đơn hàng chi tiết admin
			Route::post('/chi-tiet-don-hang/{id}','OrderController@getListDetailOrder')->name('getListDetailOrderAdmin')->middleware('CheckLogout');
			# Hiển thị đơn hàng chi tiết sale
			Route::post('/chi-tiet-don-hang-sale/{id}','order_saleController@getListDetailOrder')->name('getListDetailOrder')->middleware('CheckLogout');
			# Hiển thị đơn hàng chi tiết keToan
			Route::post('/chi-tiet-don-hang-keToan/{id}','order_keToanController@getListDetailOrder')->name('getListDetailOrderKeToan')->middleware('CheckLogout');
			# Thay đổi commissions
			Route::post('/change-commissions','OrderController@changeCommissions')->name('changeCommissions')->middleware('CheckLogout');
			# Lấy tổng tiền của sale của đơn hàng
			Route::post('/commissions-sale','order_saleController@orderCommissions')->name('orderCommissions')->middleware('CheckLogout');
			# đơn hàng bên kế toán
			Route::get('/don-hang-ke-toan/{id}','order_keToanController@orderkeToan')->name('orderkeToan')->middleware('CheckLogout');
			# thông báo đơn hàng mới admin
			Route::post('/notify_cart_admin','notificationController@notify_order')->name('notify_order')->middleware('CheckLogout');
			# thông báo đơn hàng mới customer
			Route::post('/notify_cart_customer','notificationController@notify_customer')->name('notify_customer')->middleware('CheckLogout');
			# thông báo đơn hàng mới sale
			Route::post('/notify_cart_sale','notificationController@notify_order_sale')->name('notify_order_sale')->middleware('CheckLogout');
			# thông báo đơn hàng mới kế toán

app/Http/Controllers/client/Ajax_edit_cartController.php
<?php

namespace App\Http\Controllers\client;
use DB;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Gloudemans\Shoppingcart\Facades\Cart;

class Ajax_edit_cartController extends Controller
{
    public function update(Request $request){
        Cart::update($request->id,['qty'=>$request->qty]);
        $string = '';
        foreach(Cart::content() as $item){
            $string .= '<tr class='.$item->rowId.'>
            <td> '.$item->id.'</td>
            <td>'.$item->name.'</td>
            <td><img src="'.asset('uploads/img_product/'.$item->options->image).'" width="80px" height="80px" alt=""></td>
            <td>
                <div class="product-quantity">
                       
                    <div class="product-quantity" style = "width:100px">
                        <span class="" ></span>
                        <input class="qty" type="" style="width:25px" value="'.$item->qty.'" name="quantity" />
                        <a class="update_cart" id="'.$item->rowId.'" onclick="return updateCart(this);"><span class="glyphicon glyphicon-repeat"></span></a>
                    </div>
                    <input type="hidden" value="'.$item->rowId.'" name="rowId" class="form-control">
                    
                    
                </div>
                
            </td>   
            <td>
                '.number_format($item->price,0,'.',',').' '.'VNĐ'.'
            </td>
            <td>
            '.number_format($item->price*$item->qty,0,'.',',').' ' .'VNĐ'.'
            </td>
            <th style="text-align:center;font-size:48px" id="'.$item->rowId.'" class="delete_row" onclick="return delete_cart(this);" ><a class="glyphicon glyphicon-trash"></a></th>
        </tr>
        <script>
            (function incrementDecrementInput() {
                var increment = document.querySelector(".product-quantity-plus");
                var decrement = document.querySelector(".product-quantity-minus");
                var input = document.querySelector(".product-quantity > input");

                // increment.addEventListener("click", function () {
                //     input.value++;
                // });

                // decrement.addEventListener("click", function () {
                //     if (input.value > 1) {
                //         input.value--;
                //     }
                });

            })();
        </script>
        
        
        ';
        }
        $count = Cart::count();
        $subtotal=Cart::subtotal();
        
        return ['string'=>$string,'count'=>$count,'subtotal'=>$subtotal];
    }
    public function delete(Request $request){
        Cart::update($request->get('id'),0);
        $count = Cart::count();
        $subtotal=Cart::subtotal();
       return ['count'=>$count,'subtotal'=>$subtotal];
    }
    public function themCart(Request $request){
        
        $id = $request->id;
        $quantity = 1;
        $tien = $request->price;
        $data = DB::table('product')->where('id',$id)->first();
        $result['id'] = $data->id;
        $result['name'] = $data->name;
        $result['qty'] = $quantity;
        $result['price'] = $tien;
        $result['weight'] = $data->price;
        $result['options']['image'] = $data->img;
        $result['options']['creater']=$data->creater;
        Cart::add($result);
        return  $count = Cart::count();
        
    }
}

app/Http/Controllers/client/Ajax_get_addressController.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use DB;
use App\district;
use App\ward;
use App\province;

class Ajax_get_addressController extends Controller
{
    public function post_Quan_huyen(Request $request){
        
        $district['district'] = district::where('_province_id',$request->get('id_TinhTP'))->get();
        
        $data = "";
            foreach ($district['district'] as $value) {
                $data .= "<option value=".$value->id.">".$value->_name."</option><br>";
            }
        $data .= "";  

        echo $data;
         
    }
    public function post_Phuong_Xa(Request $request){
        $ward['ward'] = ward::where('_district_id',$request->get('id_Quan'))->get();
        
        $data = "";
            foreach ($ward['ward'] as $value) {
                $data .= "<option value=".$value->id.">".$value->_name."</option><br>";
            }
        $data .= "";  

        echo $data;
    }
}

app/Http/Controllers/client/BlogController.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\blog;
use DB;
use App\comment;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\URL;
class BlogController extends Controller
{
    public function getBlog(){
        $blog = blog::all();
    	return view('client.blog',['blog' => $blog]);
    }
    public function getDetailBlog($id){
        $url = URL::current();
        $data = DB::table('blog')->where('id',$id)->get();
        $comment = DB::table('comment')->where('id_obj',$id)->orderBy('created_at','ASC')->get();
        
        return view('client.chi-tiet-blog',['data'=>$data,'id'=>$id,'comment'=>$comment,'url'=>$url]);
    }
    public function postcomment_blog(Request $request)
    {
        if(Auth::check()){
            comment::insert([
                'content'=>$request->content,
                'id_check'=>1,
                'id_obj' =>$request->id,
                'id_user'=>Auth()->user()->id,
                'created_at'=> new \DateTime(),
            ]);
            return back()->with('success','Bình luận thành công');
        }else{
            return view('client.login');
        }
        
    }
}

app/Http/Controllers/client/CheckoutController.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Session;
use DB;
session_start();
class CheckoutController extends Controller
{
    public function login_checkout(){

    }
}

app/Http/Controllers/client/ContactController.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Mail;
use App\Mail\LienHe;
class ContactController extends Controller
{
    public function getContact(){
    	return view('client.contact');
    }
    public function lienhe(Request $request){
        $name = $request->name;
        $email = $request->email;
        $phone = $request->phone;
        $content = $request->content;
        $data = [
            'name' => $name,
            'email' => $email,
            'phone' => $phone,
            'content' => $content
        ];
    
       Mail::send('client.mai_lienhe', $data, function ($message) use ($email) {
           $message->to($email)->subject("Câu hỏi khách hàng");
       });
       return redirect('/');
    }
}

app/Http/Controllers/client/PaymentControler.php
<?php

namespace App\Http\Controllers\client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\province;
use DB;
use App\contact;
use Session;
class PaymentControler extends Controller
{
    public function getPayment(){
        return redirect('/thanh-toan');
    }
    public function postPayment(Request $request){
        Session::put('name', $request->name); 
        Session::put('city', $request->get_city); 
        Session::put('town', $request->get_town); 
        Session::put('phone', $request->phone); 
        Session::put('email', $request->email); 
        Session::put('village', $request->get_village); 
        Session::put('street', $request->street); 
        Session::put('check', 1); 
        
        return view('client.payment');   
    }
}

resources/views/client/checkout.blade.php
@extends('client.master')
@section('title','Home')
<link rel="stylesheet" href="css/style.css" type="text/css" media="all" /><!-- Style-CSS -->
<link href="css/font-awesome.css" rel="stylesheet"><!-- font-awesome-icons -->

@section('content')
<section class="signin-form">
    <div class="container-fluid">
        <div class="wrapper">
            <div class="logo text-center top-bottom-gap">
            
            </div>
            <div class="form34">
                <h4 class="form-head">Xác nhận thông tin</h4>
               
                <div class="form-34or">
                    <span class="pros">
                        <span>or</span>
                    </span>
                </div>
                <form action="{{route('postPayment')}}" method="post" id="checkout">
                @csrf
                    <div class="">
                        <p class="text-head">Tên Khách</p>
                        <input type="text" name="name" class="input" value="" placeholder="" required="" />
                    </div>
                    <div class="">
                        <p class="text-head">Số điện thoại</p>
                        <input type="text" name="phone" class="input" value="" placeholder="" required="" />
                    </div>
                    <div class="">
                        <p class="text-head">Email</p>
                        <input type="text" name="email" class="input" value="" email="true" placeholder="" required="" />
                    </div>
                   
                    <div class="">
                        <p>Địa chỉ</p>
                        <select class="input" name="city" id="city" selected="get_val()" value="">
                        <option value="volvo">--Mời bạn chọn Tỉnh/Thành phố--</option>
                        @foreach($citys as $city)
                        <option  value="{{$city->id}}">{{$city->_name}}</option>                   
                        @endforeach
                    </select>
                    </div>

                     <div class="">
                       
                        <select class="input" name="town" id="town" >
                        <option value="volvo">--Mời bạn chọn Quận/Huyện--</option>
                        @foreach($citys as $city)
                        <option value="{{$city->id}}">{{$city->_name}}</option>
                        
                        @endforeach
                    </select>
                    </div>

                     <div class="">
                       
                        <select class="input" name="village" id="PhuongXa">
                        <option value="volvo">--Mời bạn chọn Phường/Xã--</option>
                        @foreach($citys as $city)
                        <option > </option>
                        @endforeach
                    </select>
                    </div> 
                    <div class="">
                        <input type="text" name="street" class="input" value="" placeholder="Địa chỉ" required="" />
                        
                    </div>
                    <input type="hidden" value="" id="get_city" placeholder="" name="get_city">
                    <input type="hidden" value="" id="get_town" placeholder="" name="get_town">
                    <input type="hidden" value="" id="get_village" placeholder="" name="get_village">
                    <button type="submit" class="btn btn-success btn-block">Tiếp tục</button>
                   
                </form>
            </div>
        </div>

    </div>
</section>
<script src="assets/js/jquery-3.5.1.min.js"></script>
<script>
    $(document).ready(function(){
            $("#city").change(function(){
                var x = $('#city :selected').text();
                $("#get_city").val(x);
            });
            $("#town").change(function(){
                var x = $('#town :selected').text();
                $("#get_town").val(x);
            });
            $("#PhuongXa").change(function(){
                var x = $('#PhuongXa :selected').text();
                $("#get_village").val(x);
            })
        })
</script>
<script type="text/javascript">
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    $(document).ready(function () {
        $("select#city").change(function () {
            var id_TinhTP = $('select#city').val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: '{{route('post_quan_huyen')}}',
                type: "POST",
                cache: false,
                data: {
                    _token: CSRF_TOKEN,
                    id_TinhTP: id_TinhTP
                },
                success: function (data) {
                    $("select#town").empty();
                    $("select#town").append(data);
                },
                error: function (error) {
                    alert("Thêm thất bại");
                }
            });

        });

    });

</script>
<script type="text/javascript">
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    $(document).ready(function () {
        $("select#town").change(function () {
            var id_Quan = $('select#town').val();
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: '{{route('post_phuong_xa')}}',
                type: "POST",
                cache: false,
                data: {
                    _token: CSRF_TOKEN,
                    id_Quan: id_Quan
                },
                success: function (data) {
                    $("select#PhuongXa").empty();
                    $("select#PhuongXa").append(data);
                },
                error: function (error) {
                    alert("Thêm thất bại");
                }
            });

        });

    });

</script>


<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>


<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
// just for the demos, avoids form submit
jQuery.validator.setDefaults({
  debug: true,
  success: "valid"
});
$( "#checkout" ).validate({
//   rules: {
//     email: {
//       required: true,
//       email: true
//     }
//   },
//   rules: {
//     password: {
//       required: true,
//       minlength: 3,
//     }
//   },
//   rules: {
//     phone: {
//       required: true,
//       number: true,
//       maxlength:10
//     },
//   rules: {
//     name: {
//       required: true,
//       number:false,
//     }
//   }

  }
  
  

});
</script>

@endsection('content')

resources/views/client/mess.blade.php
Xin Chào bạn chúng tôi cung cấp đổi mật khẩu mới cho bạn là : 
<a href="{{$url}}">Bấm vào đây</a>

resources/views/client/payment.blade.php
@extends('client.master')
@section('title','Thanh Toán')
@section('content')

<style type="text/css">
    .shop-tb{
        overflow: auto;
    }
    table{
        text-align: center;
        width: 100%;
    }
    th{
        min-width: 150px;
        padding: 10px 0;
    }
    th button{
        background: black;
        color: white;
        padding: 5px 10px;
        outline: none;
    }
    .table-p{
        border: 1px solid;
    padding: 10px 10px;
    }
</style>
<?php 
    $content = Cart::content();
    $count = Cart::count();
?>
<div class="container">
<form action="{{route('order.store')}}" method="post">
@csrf
    <div class="shop-tb mt-5">
        <table border="1">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Số lượng</th>
                <th>Giá</th>
                <th>Tổng</th>
                
            </tr>
            @foreach($content as $result)
            <tr>
                <td>{{$result->id}}</td>
                <td>{{$result->name}}</td>
                <td>{{$result->qty}}</td>
                <td>
                {{$result->price.' '.'VNĐ'}}
                </td>
                <td>{{$result->price*$result->qty}}</td>
               
            </tr>
           

            @endforeach
        </table>
    </div>
    <div class="table-p mt-5">
            <div class="table-p-content">
                <div class="row">
                    <div class="col-md-2 col-4">
                        <span><b>Thành Tiền:</b></span>
                    </div>
                    <div class="col-md-10 col-8">
                    <p>{{Cart::subtotal().'VNĐ'}}</p>
                    <input type="hidden" name="total_price" value="{{Cart::subtotal()}}">
                    <input type="hidden" name="qty" value="{{$result->qty}}">
                    <input type="hidden" name="id_prod" value="{{$result->id}}">
                    <input type="hidden" name="id_create" value="{{$result->options->creater}}">
                    <input type="hidden" name="soluong" value="{{$count}}">

                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2 col-4">
                        <span><b>Tên khách:</b></span>
                    </div>
                    <div class="col-md-10 col-8">
                        <span><p>{{session('name')}}</p></span>
                        <input type="hidden" name="name" value="{{session('name')}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2 col-4">
                        <span><b>Số Điện Thoại:</b></span>
                        
                    </div>
                    <div class="col-md-10 col-8">
                        <span><p>{{session('phone')}}</p></span>
                        <input type="hidden" name="phone" value="{{session('phone')}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2 col-4">
                        <span><b>Email:</b></span>
                        
                    </div>
                    <div class="col-md-10 col-8">
                        <span><p>{{session('email')}}</p></span>
                        <input type="hidden" name="email" value="{{session('email')}}">
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2 col-4">
                        <span><b>Địa Chỉ</b></span>
                    </div>
                    <div class="col-md-10 col-8">
                    <span><p>{{session('city')}}-{{session('town')}}-{{session('village')}}-{{session('street')}}</p></span>   
                    <input type="hidden" name="address" value="{{session('city')}}-{{session('town')}}-{{session('village')}}-{{session('street')}}">
                    </div>
                </div>
            </div>
        </div>

    <div class="text-center mt-5 mb-5">

        <button type="submit" class="btn btn-primary">Thanh Toán</button>
        <button type="button" class="btn btn-primary">Hủy</button>
    </div>
    </form>
</div>


    <script src="asset/js/jquery.min.js" defer></script>
    <script src="asset/bootstrap/js/bootstrap.min.js" defer></script>

@endsection('content')

resources/views/client/thongbao.blade.php
<div style="margin:auto">
    <h1>Bạn vui lòng kiểm tra hòm thư email của bạn</h1>
    <a href="https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin">Bấm vào đây</a>
</div>

resources/views/client/xacthuc.blade.php
<h3>Xin chào {{$name}},</h3>
<br>
<p>Chúng tôi là của hàng Shop Mart.<br> Cảm ơn bạn đã mua hàng của chúng tôi .Chúng tôi sẽ giao hàng cho bạn sớm nhất trong 3 ngày.Theo thông tin bạn cung cấp là <br>
    Số điện thoại : {{$phone}} <br>
    Email         : {{$email}} <br>
    Địa chỉ       : {{$address}}
</p>
<br>
<p>Xin trân trọng cảm ơn</p>